import '../handlers/firebase.dart';
import '../handlers/user_data.dart';

class LangHandler {
  List<String> _langList = [
    'English',
    'Français',
    'Español',
    'Русский',
    'Italiano',
    'Português',
    'Polski',
    'Deutsche',
    'Ελληνικά',
    '日本人',
    'עברית',
  ];

  final Map _lang = {
    'English': {
      'locale_lower': 'en',
      'locale_upper': 'US',
      'home_title': 'Prophecy Is Upon You',
      'history_button': 'My History',
      'history_title': 'What We Already Know',
      'history_details_button': 'Dive In',
      'new_prophecy_button': 'My Unknown',
      'new_prophecy_title': 'Seeking For Knowledge?',
      'new_prophecy_full_name': 'Full Name',
      'new_prophecy_text_name': 'What Is Your Name?',
      'new_prophecy_text_birthday': 'What Is Your Birthday?',
      'new_prophecy_date_button': 'Select Date',
      'new_prophecy_submit_button': 'Seek Knowledge',
      'date_of_prophecy': 'Date of prophecy',
      'date_of_birth': 'Date of birth',
      'prophecy_info_title': 'Precious Knowledge',
      'prophecy_back_button': 'Go Back',
      'personal_life': 'personal life',
      'profession': 'profession',
      'health': 'health',
      'travel': 'travel',
      'emotions': 'emotions',
      'luck': 'luck',
      'name_required': 'Name is required',
    },
    'Français': {
      'locale_lower': 'fr',
      'locale_upper': 'FR',
      'home_title': 'La prophétie est sur toi',
      'history_button': 'Mon Histoire',
      'history_title': 'Ce que nous savons déjà',
      'history_details_button': 'Plonger',
      'new_prophecy_button': 'Mon Inconnu',
      'new_prophecy_title': 'À la recherche de connaissances?',
      'new_prophecy_full_name': 'Nom complet',
      'new_prophecy_text_name': 'Quel est votre nom?',
      'new_prophecy_text_birthday': 'Quel est ton anniversaire?',
      'new_prophecy_date_button': 'Sélectionner une date',
      'new_prophecy_submit_button': 'Rechercher la connaissance',
      'date_of_prophecy': 'Date de la prophétie',
      'date_of_birth': 'Date de naissance',
      'prophecy_info_title': 'Précieuse connaissance',
      'prophecy_back_button': 'Retourner',
      'personal_life': 'vie privée',
      'profession': 'la profession',
      'health': 'la santé',
      'travel': 'Voyage',
      'emotions': 'émotions',
      'luck': 'la chance',
      'name_required': 'Le nom est requis',
    },
    'Español': {
      'locale_lower': 'es',
      'locale_upper': 'ES',
      'home_title': 'La profecía está sobre ti',
      'history_button': 'Mi Historia',
      'history_title': 'Lo que ya sabemos',
      'history_details_button': 'Buceo en',
      'new_prophecy_button': 'Mi Desconocido',
      'new_prophecy_title': '¿Buscando conocimiento?',
      'new_prophecy_full_name': 'Nombre completo',
      'new_prophecy_text_name': '¿Cuál es tu nombre?',
      'new_prophecy_text_birthday': '¿Cuando es tu cumpleaños?',
      'new_prophecy_date_button': 'Seleccione fecha',
      'new_prophecy_submit_button': 'Buscar el conocimiento',
      'date_of_prophecy': 'Fecha de profecia',
      'date_of_birth': 'Fecha de nacimiento',
      'prophecy_info_title': 'Conocimiento Precioso',
      'prophecy_back_button': 'Regresa',
      'personal_life': 'vida personal',
      'profession': 'la profesión',
      'health': 'la salud',
      'travel': 'el viaje',
      'emotions': 'emociones',
      'luck': 'la suerte',
      'name_required': 'Se requiere el nombre',
    },
    'Русский': {
      'locale_lower': 'ru',
      'locale_upper': 'RU',
      'home_title': 'Пророчество над тобой',
      'history_button': 'Моя История',
      'history_title': 'Что мы уже знаем',
      'history_details_button': 'Нырнуть глубже',
      'new_prophecy_button': 'Неизвестное',
      'new_prophecy_title': 'В поисках знаний?',
      'new_prophecy_full_name': 'Полное имя',
      'new_prophecy_text_name': 'Как тебя зовут?',
      'new_prophecy_text_birthday': 'Когда твой день рождения?',
      'new_prophecy_date_button': 'Выбери день',
      'new_prophecy_submit_button': 'Искать Знания',
      'date_of_prophecy': 'Дата предсказания',
      'date_of_birth': 'Дата рождения',
      'prophecy_info_title': 'Драгоценные Знания',
      'prophecy_back_button': 'Назад',
      'personal_life': 'Личная жизнь',
      'profession': 'профессия',
      'health': 'здоровье',
      'travel': 'путешествия',
      'emotions': 'эмоции',
      'luck': 'удача',
      'name_required': 'Имя обязательно',
    },
    'Italiano': {
      'locale_lower': 'it',
      'locale_upper': 'IT',
      'home_title': 'La profezia è su di te',
      'history_button': 'La Mia Storia',
      'history_title': 'Cosa sappiamo già',
      'history_details_button': 'Gettarsi',
      'new_prophecy_button': 'Il Mio Sconosciuto',
      'new_prophecy_title': 'Cerco la conoscenza?',
      'new_prophecy_full_name': 'Nome e cognome',
      'new_prophecy_text_name': 'Come ti chiami?',
      'new_prophecy_text_birthday': 'Quando è il tuo compleanno?',
      'new_prophecy_date_button': 'Seleziona la data',
      'new_prophecy_submit_button': 'Cerca la Conoscenza',
      'date_of_prophecy': 'Data della profezia',
      'date_of_birth': 'Data di nascita',
      'prophecy_info_title': 'Conoscenza Preziosa',
      'prophecy_back_button': 'Torna indietro',
      'personal_life': 'vita privata',
      'profession': 'la professione',
      'health': 'la salute',
      'travel': 'viaggio',
      'emotions': 'emozioni',
      'luck': 'la fortuna',
      'name_required': 'Il nome è obbligatorio',
    },
    'Português': {
      'locale_lower': 'pt',
      'locale_upper': 'PT',
      'home_title': 'Profecia é sobre você',
      'history_button': 'Minha história',
      'history_title': 'O que já sabemos',
      'history_details_button': 'Mergulhe',
      'new_prophecy_button': 'Meu desconhecido',
      'new_prophecy_title': 'Buscando por conhecimento?',
      'new_prophecy_full_name': 'Nome completo',
      'new_prophecy_text_name': 'Qual é o seu nome?',
      'new_prophecy_text_birthday': 'Que dia é seu aniversário?',
      'new_prophecy_date_button': 'Selecione a data',
      'new_prophecy_submit_button': 'Busque conhecimento',
      'date_of_prophecy': 'Data da profecia',
      'date_of_birth': 'Data de nascimento',
      'prophecy_info_title': 'Conhecimento Precioso',
      'prophecy_back_button': 'Volte',
      'personal_life': 'vida pessoal',
      'profession': 'a profissão',
      'health': 'a saúde',
      'travel': 'viagem',
      'emotions': 'emoções',
      'luck': 'a sorte',
      'name_required': 'Nome é obrigatório',
    },
    'Polski': {
      'locale_lower': 'pl',
      'locale_upper': 'PL',
      'home_title': 'Proroctwo jest na tobie',
      'history_button': 'Moja historia',
      'history_title': 'Co już wiemy',
      'history_details_button': 'Zanurkować',
      'new_prophecy_button': 'Mój Nieznany',
      'new_prophecy_title': 'Szukasz wiedzy?',
      'new_prophecy_full_name': 'Pełne imię i nazwisko',
      'new_prophecy_text_name': 'Jak masz na imię?',
      'new_prophecy_text_birthday': 'Kiedy masz urodziny?',
      'new_prophecy_date_button': 'Wybierz datę',
      'new_prophecy_submit_button': 'Poszukiwać wiedzy',
      'date_of_prophecy': 'Data proroctwa',
      'date_of_birth': 'Data urodzenia',
      'prophecy_info_title': 'Cenna wiedza',
      'prophecy_back_button': 'Wróć',
      'personal_life': 'życie osobiste',
      'profession': 'zawód',
      'health': 'zdrowie',
      'travel': 'podróżować',
      'emotions': 'emocje',
      'luck': 'szczęście',
      'name_required': 'Imie jest wymagane',
    },
    'Deutsche': {
      'locale_lower': 'de',
      'locale_upper': 'DE',
      'home_title': 'Prophezeiung ist auf dir',
      'history_button': 'Meine Geschichte',
      'history_title': 'Was wir bereits wissen',
      'history_details_button': 'Eintauchen',
      'new_prophecy_button': 'Mein Unbekannter',
      'new_prophecy_title': 'Auf der Suche nach Wissen?',
      'new_prophecy_full_name': 'Vollständiger Name',
      'new_prophecy_text_name': 'Wie heißen Sie?',
      'new_prophecy_text_birthday': 'Wann hast du Geburtstag?',
      'new_prophecy_date_button': 'Datum auswählen',
      'new_prophecy_submit_button': 'Wissen suchen',
      'date_of_prophecy': 'Datum der Prophezeiung',
      'date_of_birth': 'Geburtsdatum',
      'prophecy_info_title': 'Wertvolles Wissen',
      'prophecy_back_button': 'Geh zurück',
      'personal_life': 'persönliches Leben',
      'profession': 'der Beruf',
      'health': 'Gesundheit',
      'travel': 'die Reise',
      'emotions': 'Emotionen',
      'luck': 'das Glück',
      'name_required': 'Name ist erforderlich',
    },
    'Ελληνικά': {
      'locale_lower': 'el',
      'locale_upper': 'EL',
      'home_title': 'Η προφητεία είναι επάνω σου',
      'history_button': 'Η ιστορία μου',
      'history_title': 'Αυτό που γνωρίζουμε ήδη',
      'history_details_button': 'Βουτάω',
      'new_prophecy_button': 'Άγνωστο μου',
      'new_prophecy_title': 'Αναζητώντας Γνώση;',
      'new_prophecy_full_name': 'Πλήρες όνομα',
      'new_prophecy_text_name': 'Πως σε λένε?',
      'new_prophecy_text_birthday': 'Ποια είναι τα γενέθλιά σας;',
      'new_prophecy_date_button': 'Επιλέξτε Ημερομηνία',
      'new_prophecy_submit_button': 'Αναζήτηση γνώσεων',
      'date_of_prophecy': 'Ημερομηνία προφητείας',
      'date_of_birth': 'Ημερομηνία γεννήσεως',
      'prophecy_info_title': 'Πολύτιμη γνώση',
      'prophecy_back_button': 'Πήγαινε πίσω',
      'personal_life': 'προσωπική ζωή',
      'profession': 'επάγγελμα',
      'health': 'υγεία',
      'travel': 'ταξίδι',
      'emotions': 'συναισθήματα',
      'luck': 'τυχη',
      'name_required': 'Απαιτείται όνομα',
    },
    '日本人': {
      'locale_lower': 'ja',
      'locale_upper': 'JA',
      'home_title': '予言はあなた次第です',
      'history_button': '私の歴史',
      'history_title': '私たちがすでに知っていること',
      'history_details_button': '飛び込む',
      'new_prophecy_button': '私の知らない',
      'new_prophecy_title': '知識を求めて？',
      'new_prophecy_full_name': 'フルネーム',
      'new_prophecy_text_name': 'お名前は何ですか？',
      'new_prophecy_text_birthday': 'あなたの誕生日は何ですか？',
      'new_prophecy_date_button': '日付を選択',
      'new_prophecy_submit_button': '知識を求める',
      'date_of_prophecy': '予言の日',
      'date_of_birth': '生年月日',
      'prophecy_info_title': '貴重な知識',
      'prophecy_back_button': '戻る',
      'personal_life': '私生活',
      'profession': '職業',
      'health': '健康',
      'travel': '旅行',
      'emotions': '感情',
      'luck': '運',
      'name_required': '名前が必要です',
    },
    'עברית': {
      'locale_lower': 'he',
      'locale_upper': 'HE',
      'home_title': 'הנבואה היא עליך',
      'history_button': 'ההיסטוריה שלי',
      'history_title': 'מה שאנחנו כבר יודעים',
      'history_details_button': 'לצלול פנימה',
      'new_prophecy_button': 'שלי לא ידוע',
      'new_prophecy_title': 'מחפש ידע?',
      'new_prophecy_full_name': 'שם מלא',
      'new_prophecy_text_name': 'מה השם שלך?',
      'new_prophecy_text_birthday': 'מה הוא יום ההולדת שלך?',
      'new_prophecy_date_button': 'בחר תאריך',
      'new_prophecy_submit_button': 'חפשו ידע',
      'date_of_prophecy': 'תאריך הנבואה',
      'date_of_birth': 'תאריך לידה',
      'prophecy_info_title': 'ידע יקר',
      'prophecy_back_button': 'תחזור',
      'personal_life': 'חיים אישיים',
      'profession': 'מקצוע',
      'health': 'בריאות',
      'travel': 'נסיעות',
      'emotions': 'רגשות',
      'luck': 'מזל',
      'name_required': 'נדרש שם',
    },
  };
  
  String chosenLang;

  void changeLanguage(String language) {
    chosenLang = language;
    firebaseHandler.sendDefaultLanguage(userData.userId, language);
    return _lang[chosenLang];
  }

  get changeLang => changeLanguage(chosenLang);

  get langChoices => _langList;
}

LangHandler langHandler = new LangHandler();
